runtime: custom
api_version: '1'
service: default
env: flexible
threadsafe: true
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10
network: {}
readiness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300
