FROM surnet/alpine-node-wkhtmltopdf:8.11.3-0.12.5-full
# confirm installation
RUN node -v
RUN npm -v

RUN wkhtmltopdf --version
RUN which wkhtmltopdf
# RUN echo "<h2>Hello World</h2>" | wkhtmltopdf --

RUN npm i -g yarn
COPY . .
RUN yarn 
#--production=true

CMD node lib/index.js
