FROM surnet/alpine-python-wkhtmltopdf:3.7.2-0.12.5-full
# confirm installation
RUN python --version
RUN wkhtmltopdf --version

RUN apt update
RUN apt install xvfb
RUN apt install xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic
RUN apt install flashplugin-nonfree

RUN pip install wkhtmltopdf

# RUN echo "<h2>Hello World</h2>" | wkhtmltopdf --

# RUN npm i -g yarn
COPY . .
WORKDIR src
CMD python main.py
# RUN yarn 
#--production=true

# CMD node lib/index.js

