name: Deploy

on: 
  push: 
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{secrets.GCP_CREDENTIALS}}
        project_id: resvuapps

    # Build and push image to Google Container Registry
    - name: Build
      run: |-
        gcloud builds submit \
          --quiet \
          --tag gcr.io/resvuapps/pdf1test

    # Deploy image to Cloud Run
    - name: Deploy
      run: |-
        gcloud run deploy pdf1test \
          --quiet \
          --region asia-northeast1 \
          --image gcr.io/resvuapps/pdf1test \
          --platform "managed" \
          --memory 2G \
          --concurrency 2 \
          --allow-unauthenticated 
          